---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 24h
  url: https://aws.github.io/eks-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
  interval: 2m
  install:
    remediation:
      retries: 3
  uninstall:
    timeout: 24h
    disableHooks: false
    keepHistory: false
  values:
    clusterName: experimental
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
